"""
This type stub file was generated by pyright.
"""

from types import ModuleType
from typing import Any

"""
Test deprecated constants custom integration.

This file is originally from homeassistant/core and modified by pytest-homeassistant-custom-component.
"""
def import_deprecated_constant(module: ModuleType, constant_name: str) -> Any:
    """Import and return deprecated constant."""
    ...

